{
 "title": "[KMinion] Unified Dashboard - Prometheus Exporter for Apache Kafka",
 "description": "Unified metrics exported by KMinion",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "highThroughputTopics",
    "query": "query_result(topk(15, avg by (topic_name) (avg_over_time(kminion_kafka_topic_high_water_mark_sum[${__range_s}s]))))"
   },
   {
    "name": "topOffsetCommitters",
    "query": "query_result(topk(5, avg by (group_id) (avg_over_time(kminion_kafka_consumer_group_offset_commits_total[${__range_s}s]))))"
   },
   {
    "name": "consumerGroup",
    "label": "Consumer Group",
    "query": "label_values(kminion_kafka_consumer_group_topic_lag, group_id)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\"}, topic_name)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Brokers",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "kminion_kafka_broker_info" }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kminion_kafka_cluster_info" }
   ]
  },
  {
   "title": "Cluster Version",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "kminion_kafka_cluster_info" }
   ]
  },
  {
   "title": "Messages in/sec",
   "type": "graph",
   "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (kubernetes_pod_name) (rate(kminion_kafka_topic_high_water_mark_sum[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Messages in/sec by topic [Top 15]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=~\"$highThroughputTopics\"}[$__rate_interval]))",
     "legendFormat": "{{topic_name}}"
    }
   ]
  },
  {
   "title": "Log Dir Size by Broker",
   "type": "graph",
   "description": "Log dir size across all log dirs, topics and partitions for a given broker.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by (broker_id) (kminion_kafka_broker_log_dir_size_total_bytes)",
     "legendFormat": "Broker {{broker_id}}"
    }
   ]
  },
  {
   "title": "Top Offset Committers [Top 5]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (group_id) (rate(kminion_kafka_consumer_group_offset_commits_total{group_id=~\"$topOffsetCommitters\"}[$__rate_interval]))",
     "legendFormat": "{{group_id}}"
    }
   ]
  },
  {
   "title": "Offset commits processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "avg by (kubernetes_pod_name) (rate(kminion_exporter_offset_consumer_records_consumed_total[$__rate_interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Consumer Groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumergroup => Topic Lag",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Messages" }
     ],
     "targets": [
      {
       "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})",
       "legendFormat": "{{group_id}} => {{topic_name}}"
      }
     ]
    },
    {
     "title": "Topic Lag",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (group_id,topic_name) (kminion_kafka_consumer_group_topic_lag{group_id=\"$consumerGroup\", topic_name=\"$topic\"})"
      }
     ]
    },
    {
     "title": "Offset Commit Rate",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (sum by (kubernetes_pod_name) (rate(kminion_kafka_consumer_group_offset_commits_total{group_id=\"$consumerGroup\"}[1m])))"
      }
     ]
    },
    {
     "title": "Messages In vs Consumed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short", "label": "Messages/s" }
     ],
     "targets": [
      {
       "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
       "legendFormat": "Incoming: {{topic_name}}"
      },
      {
       "expr": "avg by (topic_name, group_id) (rate(kminion_kafka_consumer_group_topic_offset_sum{group_id=\"$consumerGroup\", topic_name=\"$topic\"}[$__rate_interval]))",
       "legendFormat": "Consuming: {{topic_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message count",
     "type": "graph",
     "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (topic_name) (kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"} - kminion_kafka_topic_low_water_mark_sum{topic_name=\"$topic\"})",
       "legendFormat": "{{topic_name}}"
      }
     ]
    },
    {
     "title": "Partition Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Cleanup Policy",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Messages in/sec",
     "type": "graph",
     "description": "Summed delta between High and Low watermark of all partitions in the given topic. Therefore not accurate for compacted topics that contain compacted records.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg by (topic_name) (rate(kminion_kafka_topic_high_water_mark_sum{topic_name=\"$topic\"}[$__rate_interval]))",
       "legendFormat": "{{topic_name}}"
      }
     ]
    },
    {
     "title": "Replication Factor",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kminion_kafka_topic_info{topic_name=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Subscribed Consumer Groups",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "kminion_kafka_consumer_group_topic_lag{topic_name=\"$topic\"}"
      }
     ]
    },
    {
     "title": "Total Log Dir Size",
     "type": "graph",
     "description": "Log dir size across all partitions and brokers for the given topic.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "avg by (topic_name) (kminion_kafka_topic_log_dir_size_total_bytes{topic_name=\"$topic\"})",
       "legendFormat": "{{topic_name}}"
      }
     ]
    },
    {
     "title": "Partitions",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "avg by (partition_id) (kminion_kafka_topic_partition_low_water_mark{topic_name=\"$topic\"})"
      },
      {
       "expr": "avg by (partition_id) (kminion_kafka_topic_partition_high_water_mark{topic_name=\"$topic\"})"
      }
     ]
    }
   ]
  }
 ]
}